services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
      target: production
    environment:
      NODE_ENV: production
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /app/server/src
          ignore:
            - node_modules/
    

  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
      target: production
    environment:
      NODE_ENV: production
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
